version: 2
jobs:
  build:
    parallelism: 1
    shell: /bin/bash --login
    working_directory: ~/CoMakery/comakery-app
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      RUBY_VER: 2.4.4
      NODE_VER: 10.13
      YARN_VER: 1.12.3
      SCHM_VER: 20160227015851
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init
    steps:
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: rvm use $RUBY_VER --default
      - run: nvm install $NODE_VER && nvm alias default $NODE_VER
      - run: 'echo ''America/Los_Angeles'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure -f noninteractive tzdata; sudo service mysql restart; sudo service postgresql restart;'
    
      - checkout

      - type: cache-restore
        key: comakery-bundle-{{ checksum "Gemfile.lock" }}
      - type: cache-restore
        key: comakery-yarn-{{ checksum "yarn.lock" }}

      - run: gem update
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: npm i -g yarn@$YARN_VER
      - run: bin/yarn install

      - type: cache-save
        key: comakery-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - type: cache-save
        key: comakery-yarn-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - run: bundle exec rake db:create db:migrate
      - run: bundle exec rake db:migrate VERSION=$SCHM_VER
      - run: git checkout db/schema.rb
      - run: bundle exec rake db:reset

      - run: yarn test
      - run: bundle exec citizen checks
      
      - type: store_test_results
        path: /tmp/circleci-test-results
      - type: store_artifacts
        path: /tmp/circleci-test-results
      - type: store_artifacts
        path: /tmp/circleci-artifacts
      - type: store_artifacts
        path: coverage
