inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'db/data_migrations/*.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0

# Avoid complex methods.
# Complex methods are hard to test and read.
# Low cyclomatic complexity is the simplest indication of code quality, readability and maintainability.
# Bypassing this check should trigger a team discussion
Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - 'app/views/**/*'

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/PerceivedComplexity:
  Max: 15

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationStyle:
  Enabled: true
  IndentationWidth: 2
  EnforcedStyle: spaces

Lint/RequireParentheses:
  Enabled: true

Metrics/ModuleLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/factories.rb'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

# Don't turn this on, it's overzealous
Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false
