require: rubocop-rspec

inherit_from: todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2

# Avoid complex methods.
# Complex methods are hard to test and read.
# Low cyclomatic complexity is the simplest indication of code quality, readability and maintainability.
# Bypassing this check should trigger a team discussion
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/views/**/*'
  Max: 5

Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/PerceivedComplexity:
  Max: 15

Layout/IndentationConsistency:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/RequireParentheses:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/factories.rb'

Rails:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

# Don't turn this on, it's overzealous
Style/MethodCallWithArgsParentheses:
  Enabled: false
