# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
#   pull_request:
#     branches: [ acceptance, master ]
#   schedule:
#     - cron: "0 2 * * 1-5"

jobs:
  ruby:
    strategy:
      matrix:
        ruby: [2.7.1]

    name: Ruby lints
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Cache Ruby dependencies
      uses: actions/cache@v1.1.2
      with:
        path: vendor/bundle
        key: ${{ matrix.ruby }}-gems1-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ matrix.ruby }}-gems1-

    - name: Set up Bundler to use cache
      run: bundle config path 'vendor/bundle'

    - name: Install Ruby dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Run Rubocop
      run: bin/rubocop

    - name: Run Erblint
      run: bin/erblint_ci

    - name: Run Brakeman
      run: bundle exec brakeman --exit-on-warn --quiet
